### ISSUE TITLE
Abstürze

### ISSUE THREAD

**Issue by Waldfeee** [marc2016/ioBroker.elero-usb-transmitter#1]
Danke für deinen Adapter, leider stürzt dieser öfters nach dem ansteuern ab. 

meinst du, dass du das machen könntest? 

Liebe Grüße

host.raspberrypi | 2021-02-23 14:45:48.336 | error | instance system.adapter.elero-usb-transmitter.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
elero-usb-transmitter.0 | 2021-02-23 14:45:47.760 | warn | (9935) Terminated (UNCAUGHT_EXCEPTION): Without reason
elero-usb-transmitter.0 | 2021-02-23 14:45:47.758 | info | (9935) terminating
elero-usb-transmitter.0 | 2021-02-23 14:45:47.738 | error | (9935) undefined
elero-usb-transmitter.0 | 2021-02-23 14:45:47.738 | error | (9935) unhandled promise rejection: undefined
elero-usb-transmitter.0 | 2021-02-23 14:45:47.736 | error | (9935) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
elero-usb-transmitter.0 | 2021-02-23 14:45:47.729 | info | (9935) state elero-usb-transmitter.0.channel_10.controlCommand changed: 32 (ack = true)
elero-usb-transmitter.0 | 2021-02-23 14:45:47.716 | info | (9935) Response from sending command 32 to device channel_10: {"header":170,"length":5,"command":77,"activeChannels":[4],"checksum":5,"status":-1,"statusCode":-1}
elero-usb-transmitter.0 | 2021-02-23 14:45:47.709 | info | (9935) state elero-usb-transmitter.0.channel_10.controlCommand changed: 32 (ack = false)
elero-usb-transmitter.0 | 2021-02-23 14:45:38.909 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.906 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.902 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.898 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.894 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.890 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.886 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.881 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.877 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.873 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:38.869 | error | (9935) Error while refreshing device: responseBytes are null..
elero-usb-transmitter.0 | 2021-02-23 14:45:35.302 | info | (9935) Refreshing info of devices.
elero-usb-transmitter.0 | 2021-02-23 14:45:35.301 | info | (9935) Active channel: 14
elero-usb-transmitter.0 | 2021-02-23 14:45:35.300 | info | (9935) Active channel: 13
elero-usb-transmitter.0 | 2021-02-23 14:45:35.300 | info | (9935) Active channel: 12
elero-usb-transmitter.0 | 2021-02-23 14:45:35.299 | info | (9935) Active channel: 11
elero-usb-transmitter.0 | 2021-02-23 14:45:35.298 | info | (9935) Active channel: 10
elero-usb-transmitter.0 | 2021-02-23 14:45:35.298 | info | (9935) Active channel: 9
elero-usb-transmitter.0 | 2021-02-23 14:45:35.297 | info | (9935) Active channel: 8
elero-usb-transmitter.0 | 2021-02-23 14:45:35.296 | info | (9935) Active channel: 7
elero-usb-transmitter.0 | 2021-02-23 14:45:35.296 | info | (9935) Active channel: 6
elero-usb-transmitter.0 | 2021-02-23 14:45:35.295 | info | (9935) Active channel: 5
elero-usb-transmitter.0 | 2021-02-23 14:45:35.294 | info | (9935) Active channel: 4
elero-usb-transmitter.0 | 2021-02-23 14:45:35.293 | info | (9935) Active channel: 3
elero-usb-transmitter.0 | 2021-02-23 14:45:35.292 | info | (9935) Active channel: 2
elero-usb-transmitter.0 | 2021-02-23 14:45:35.289 | info | (9935) Active channel: 1
elero-usb-transmitter.0 | 2021-02-23 14:45:35.197 | info | (9935) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.elero-usb-transmitter, node: v12.20.2, js-controller: 3.2.16
host.raspberrypi | 2021-02-23 14:45:33.745 | info | instance system.adapter.elero-usb-transmitter.0 started with pid 9935
host.raspberrypi | 2021-02-23 14:45:03.706 | info | Restart adapter system.adapter.elero-usb-transmitter.0 because enabled

**Comment by marc2016** [comment]
Hi Waldfeee,

ich schaue mir das gerne mal an. Passiert das bei jedem ansteuern? Wie viele Geräte hast Du mit dem Stick verbunden?

Viele Grüße

**Comment by Waldfeee** [comment]
Hey, 

ja, dass passiert bei jedem Ansteuern. 

Zur Konkretisierung: 
Adapter startet beim ersten Mal „normal“, allerdings kommt pro Kanal der error: responseBytes are null. Der status jedes einzelnen Rolladens wird aber korrekt angezeigt. Auch Änderungen mit der Fernbedienung von Elero werden registriert. 

sobald aber ein Rolladen von ioBroker aus angesteuert wird, geht das Signal auch raus und er bewegt sich, allerdings stürzt der Adapter ab. Danach braucht er 7-10 Neustarts, bis er sich wieder „einfängt“.

insgesamt sind 14 Rolläden verbunden!

Vielen Dank!

**Comment by marc2016** [comment]
Ich habe gerade die Version 0.0.3 auf github hochgeladen. In der Version sind ein paar Log Ausgaben dazu gekommen, die uns bei der Fehlersuche helfen sollen. Bitte installiere die Version und stelle das Log auf Debug. Poste dann nochmal bitte das Log hier.

**Comment by Waldfeee** [comment]
wird erledigt! stecke gerade nur mitten im umzug, weswegen es evtl. etwas dauert!

danke schonmal :)
