### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.5.2

### ISSUE THREAD

**Issue by GermanBluefox** [marc2016/ioBroker.elero-usb-transmitter#4]
# Think about adding version 0.5.2 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.5.2** (331 days old)
**Installs**: stable=**0** (0%), latest=**9** (90%), total=**10**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by marc2016** [comment]
Created PR https://github.com/ioBroker/ioBroker.repositories/pull/2455
:-)

**Comment by mcm1957** [comment]
PR needs to be fixed

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.5.2 but the current stable version is already 0.5.2.

So this issue should be closed.
